version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: local_db
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d local_db -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
  django:
    build:
      context: .
    environment:
      DB_NAME: "local_db"
      DB_USER: "postgres"
      DB_USER_PASSWORD: "root"
      DB_HOST: "postgres"
      DB_PORT: 5432
      ALLOWED_HOSTS: 'localhost, 127.0.0.1, 0.0.0.0'
    ports:
     - "8000:8000"
    depends_on:
     postgres:
        condition: service_healthy

volumes:
  db-data: